### PR TITLE
fix unit test

### LINKED ISSUE #30: ng test failed due to MockUserService is not found
Just checkout the master code, and realize ```MockUserService``` is not under ```app/shared/mocks```. Is it deleted?

### PR DESCRIPTION
**Pull request by bfwg**
Closes #30 

@zhengye1 
Please give the fix a review by running `npm run test`.

Thanks!

### CODE REVIEW

**Comment by zhengye1** [comment]
How to checkout the other branch?

**Comment by bfwg** [comment]
Try 
```
git fetch origin
git checkout -b fix-unit-test origin/fix-unit-test
```

**Comment by zhengye1** [comment]
Tried, but I got following issue:
image

**Comment by bfwg** [comment]
Oh, my mistake, try just do `git checkout fix-unit-test`

**Comment by zhengye1** [comment]
Hmmm... still not working...
image

**Comment by bfwg** [comment]
Weird, try without the `--depth 1`? Like `git clone https://github.com/bfwg/angular-spring-starter.git` follow by `git branch -a`. What do you see?

**Comment by zhengye1** [comment]
Now I see all the branch
image

try to check out and I got 
image


Seems working, checking the unit test now

**Comment by zhengye1** [comment]
Unit test is passed, it can be merge to master now.

**Pull request merged**
